
name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout source code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build docker image 
        run: docker build -t  bandariajaykumar/my-portfolio-website .

      - name: publish  image to docker hub
        run: docker push  bandariajaykumar/my-portfolio-website:latest
  deploy:
   needs: build
   runs-on: [aws-ec2]
   steps:
     - name: pull the image for the docker hub
       run: sudo docker pull bandariajaykumar/my-portfolio-website:latest

     - name: delete old docker container
       run: sudo docker rm -f my-portfolio-website

     - name: runing the container
       run: sudo docker run -d -p 5173:5173 --name my-portfolio-website bandariajaykumar/my-portfolio-website


